# Site settings
title: Neatline
email: neatline@collab.itc.virginia.edu
description: "Neatline allows scholars, students, and curators to tell stories with maps and timelines."
url: ""

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

exclude: ["README.md", "Procfile", "Gruntfile.js", "changelog.md", "Gemfile", "Gemfile.lock", "node_modules", "bower_components", "scss", "config.rb", "package.json", "LICENSE", "bower.json"]
