# Site settings
title: Neatline
email: neatline@collab.itc.virginia.edu
description: "Neatline allows scholars, students, and curators to tell stories with maps and timelines."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude: ["README.md", "Procfile", "Gruntfile.js", "changelog.md", "Gemfile", "Gemfile.lock", "node_modules", "bower_components", "scss", "config.rb", "package.json", "LICENSE", "bower.json"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections_dir: collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "docs"
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "assets/images/docs"
    values:
      image: true
  - scope:
      path: "assets/wp-images/uploads/2014/01"
    values:
      image: true
  - scope:
      path: "pages"
    values:
      order: 10
  - scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      og_type: "article"
  - scope:
      path: ""
      type: "pages"
    values:
      is_page: true
      og_type: "website"
