# Site settings
title: Neatline
email: your-email@domain.com
description: "Neatline is..."
baseurl: "http://localhost:4000"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

