# Site settings
title: Neatline
email: neatline@collab.itc.virginia.edu
description: "Neatline allows scholars, students, and curators to tell stories with maps and timelines."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude: ["README.md", "Procfile", "Gruntfile.js", "changelog.md", "Gemfile", "Gemfile.lock", "node_modules", "bower_components", "scss", "config.rb", "package.json", "LICENSE", "bower.json"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


collections_dir: collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/
  docs-s:
    output: true
    permalink: /:collection/:name/
  use-cases:
    output: true
    permalink: /:collection/:name/
  tutorials:
    output: true
    permalink: /:collection/:name/


defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "docs"
  - scope:
      path: ""
      type: "docs-s"
    values:
      layout: "docs-s" 

